mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cyl_hlj.pojo

#数据库连接池
spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/db_pss?characterEncoding=UTF-8
